project_id = "iwthriddasxzbjddpzzf"

[functions.send-sms-invite]
verify_jwt = true

[functions.revenuecat_webhook]
verify_jwt = false

[functions.verify-password]
verify_jwt = true

[functions.delete-account]
verify_jwt = true

[functions.paymentwall-widget-key]
verify_jwt = false

[functions.amazon-affiliate-sync]
verify_jwt = false

[functions.test-messagebird]
verify_jwt = false

[functions.process-referral-signup]
verify_jwt = false

[functions.send-referral-invite]
verify_jwt = true

[functions.get-place-recommendations]
verify_jwt = true

[functions.generate-recommendation]
verify_jwt = true

[functions.track-recommendation-event]
verify_jwt = true

[functions.moyasar-webhook]
verify_jwt = false

[functions.send-renewal-reminders]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.smart-group-suggestions]
verify_jwt = true

[functions.ask-recommendation]
verify_jwt = true

[functions.generate-trip-plan]
verify_jwt = true

[functions.grant-monthly-credits]
verify_jwt = false

[functions.paymentwall-pingback]
verify_jwt = false
