project_id = "iwthriddasxzbjddpzzf"

[functions.send-sms-invite]
verify_jwt = true

[functions.revenuecat_webhook]
verify_jwt = false

[functions.verify-password]
verify_jwt = true

[functions.delete-account]
verify_jwt = true

[functions.amazon-affiliate-sync]
verify_jwt = false

[functions.test-messagebird]
verify_jwt = false
